export const SCORING_MAX_ACTION_LENGTH = 10_000;
export const SCORING_MAX_OUTPUT_LENGTH = 100_000;
export const SCORING_MAX_COMBINED_LENGTH =
  SCORING_MAX_ACTION_LENGTH + SCORING_MAX_OUTPUT_LENGTH + 1;
export const SCORING_MAX_PATTERN_LENGTH = 256;
export const SCORING_REGEX_TIMEOUT_MS = 100;
export const SCORING_REGEX_MAX_CONCURRENCY = 4;
export const SCORING_REGEX_MAX_QUEUE = 64;
